export const LANG_EN_NAME = 'en';

export const LANG_EN_TRANS = {
    'login': 'login',
    'register': 'register',
    'username': 'username',
    'password': 'password',
    'loginTitle': 'Login',
    'registerTitle': 'Register',
    'passwordRepeat': 'repeat password',
    'cancel': 'cancel',
    'home': 'Home',
    'welcome': 'Welcome',
    'character': 'Character',
    'logout': 'Logout',
    'race': 'Race',
    'class': 'Class',
    'talent': 'Talent',
    'save': 'Save',

    // Instances
    'ony': 'Onyxia\'s Lair',
    'mc': 'Molten Core',
    'zg': 'Zul\'Gurub',
    'bwl': 'Blackwinglair',
    'aq20': 'Ruins of Ahn\'Qiraj',
    'aq40': 'Temple of Ahn\'Qiraj',
    'nax': 'Naxxramas',
    'wb': 'World Bosses',

    // Bosses
    'onyxia': 'Onyxia',

    'luci': 'Lucifron',
    'magma': 'Magmadar',
    'gehe': 'Gehennas',
    'garr': 'Garr',
    'shazz': 'Shazzrah',
    'geddon': 'Baron Geddon',
    'sulfuron': 'Sulfuron Herold',
    'gole': 'Golemagg the Incinerator',
    'majo': 'Majordomo Executus',
    'raggi': 'Ragnaros',
    'mctrash': 'Trash',

    'jeklik': 'High Priestess Jeklik',
    'venoxis': 'High Priest Venoxis',
    'marli': 'High Priestess Mar\'li',
    'thekal': 'High Priest Thekal',
    'arlokk': 'High Priestess Arlokk',
    'mando': 'Bloodlord Mandokir',
    'jindo': 'Jin\'do the Hexxer',
    'ghaz': 'Gahz\'ranka',
    'madness': 'Edge of Madness',
    'hakkar' :'Hakkar',
    'zgtrash': 'Trash',

    'razo': 'Razorgore the Untamed',
    'vael': 'Vaelastrasz the Corrupt',
    'lash': 'Broodlord Lashlayer',
    'flamegor': 'Flamegor',
    'ebonroc':  'Ebonroc',
    'firemaw': 'Firemaw',
    'chrommi': 'Chromaggus',
    'nef': 'Nefarian',
    'bwltrash': 'Trash',

    'kurinaxx': 'Kurinaxx',
    'rajaxx': 'General Rajaxx',
    'moam': 'Moam',
    'buru': 'Buru the Gorger',
    'aya': 'Ayamiss the Hunter',
    'ossi': 'Ossirian the Unscarred',
    'aq20trash': 'Trash',

    'skeram': 'The Prophet Skeram',
    'bugs': 'Silithid Royalty',
    'sartura': 'Battleguard Sartura',
    'fankriss': 'Fankriss the Unyielding',
    'visci': 'Viscidus',
    'huhu': 'Princess Huhuran',
    'twins': 'The Twin Emperors',
    'ouro': 'Ouro',
    'cthun': 'C\'Thun',
    'aq40trash': 'Trash',

    'anub': 'Anub\'Rekhan',
    'widow': 'Grand Widow Faerlina',
    'maexxna': 'Maexxna',
    'noth': 'Noth the Plaguebringer',
    'heigan': 'Heigan the Unclean',
    'loatheb': 'Loatheb',
    'razuvi': 'Instructor Razuvious',
    'gothik': 'Gothik the Harvester',
    'horsement': 'The Four Horsemen',
    'patchwork': 'Patchwork',
    'grobbulus': 'Grobbulus',
    'gluth': 'Gluth',
    'thaddius': 'Thaddius',
    'saphiron': 'Sapphiron',
    'kel': 'Kel\'Thuzad',
    'naxtrash': 'Trash',

    'kazzak': 'Kazzak',
    'azu': 'Azuregos',
    'ysondre': 'Ysondre',
    'lethon': 'Lethon',
    'taerar': 'Taerar',
    'emeriss': 'Emeriss',

    // Classes
    'priest': 'Priest',
    'mage': 'Mage',
    'wl': 'Warlock',
    'rogue': 'Rogue',
    'druid': 'Druid',
    'hunter': 'Hunter',
    'shami': 'Shaman',
    'warri': 'Warrior',
    'pala': 'Paladin',

    // Talents
    'holypr': 'Holy',
    'disc': 'Discipline',
    'shadow': 'Shadow',

    'frost': 'Frost',
    'fire': 'Fire',
    'arcane': 'Arcane',

    'affli': 'Affliction',
    'destro': 'Descruction',
    'demo': 'Demonology',

    'combat': 'Combat',
    'sub': 'Subtlety',
    'ass': 'Assassination',

    'feral': 'Feral',
    'balance': 'Balance',
    'restod': 'Restoration',

    'surv': 'Survival',
    'mark': 'Marksmanship',
    'beast': 'Beast Mastery',

    'restos': 'Restoration',
    'enh': 'Enhancement',
    'ele': 'Elemental',

    'protw': 'Protection',
    'arms': 'Arms',
    'fury': 'Fury',

    'holypa': 'Holy',
    'protp': 'Protection',
    'ret': 'Retribution',

    // Factions
    'ally': 'Alliance',
    'horde': 'Horde',

    // Races
    'gnome': 'Gnome',
    'dwarf': 'Dwarf',
    'human': 'Human',
    'ne': 'Nightelf',
    'ud': 'Undead',
    'orc': 'Orc',
    'troll': 'Troll',
    'tauren': 'Tauren',

    // Items
};